#Constantes
SIZE = SCREEN_W, SCREEN_H = 1024, 768
SPEED = [2, 2]
FONT_SIZE = 30
BACKGROUND_COLOR = 0, 0, 0
MUSIC_PATH = 'resources/music.ogg'
SOUND_COIN_PATH = 'resources/coin.ogg'
SOUND_HURT_PATH = 'resources/hurt.ogg'
MAP1_PATH = 'resources/level1.txt'
MAP2_PATH = 'resources/level2.txt'
MAP3_PATH = 'resources/level3.txt'
MAP4_PATH = 'resources/level4.txt'
MAP5_PATH = 'resources/level5.txt'
MAP_LIST = [MAP1_PATH, MAP2_PATH, MAP3_PATH, MAP4_PATH, MAP5_PATH]
OBJECTS1_PATH = 'resources/level1-objects.json'
OBJECTS2_PATH = 'resources/level2-objects.json'
OBJECTS3_PATH = 'resources/level3-objects.json'
OBJECTS4_PATH = 'resources/level4-objects.json'
OBJECTS5_PATH = 'resources/level5-objects.json'
OBJECT_LIST = [OBJECTS1_PATH,OBJECTS2_PATH,OBJECTS3_PATH,OBJECTS4_PATH,OBJECTS5_PATH]
TILE_FLOOR1_PATH = 'resources/floor1.png'
TILE_WALL_PATH = 'resources/wall.png'
TILE_FLOOR2_PATH = 'resources/floor2.png'
TILE_FLOOR3_PATH = 'resources/floor3.png'
HERO_SURFACE_RUNNING_PATH = 'resources/sheet_hero_walk.png'
HERO_RUNNING_FRAMES = 3
HERO_SURFACE_IDLE_PATH = 'resources/sheet_hero_idle.png'
HERO_IDLE_FRAMES = 8
HERO_SURFACE_HURT_PATH = 'resources/sheet_hero_hurt.png'
HERO_HURT_FRAMES = 4
TILE_W = 64
TILE_H = 64
TILE_WALL = 1
TILE_FLOOR = 0
TILE_ENTRY = 2
TILE_EXIT = 3
MAP_W = 12
MAP_H = 12
HERO_HP_MAX = 3
HERO_SPEED = 8
HERO_COLISION_OFFSET = 12
HERO_SIZE_W = 32
HERO_SIZE_H = 32
MAX_SCORE = 1000
SCORE_TICK = 250 #Milisegundos en los que tarda en bajar 1 punto de score
SCORE_TEXT_OFFSET = 16
HURT_ANIMATION_TICKRATE = 1000
#Enum de estados de heroe
HERO_IDLE = 0
HERO_RUN = 1
HERO_HURT = 2
FONT_TYPE = 'Arial'
OBJECT_GOLD_PATH = 'resources/soupdungeon_2x/gold_pile_16_2x.png'
OBJECT_TRAP_PATH = 'resources/soupdungeon_2x/crystal_wall_lightred_2x.png'
ANIMATION_TICKRATE = 150
LOSING_SURFACE = 'resources/losingScreen.png'
WINNING_SURFACE = 'resources/WinningScreen.png'
HEART_1_SURFACE = 'resources/Corazon1.png'
HEART_2_SURFACE = 'resources/Corazon2.png'
HEART_3_SURFACE = 'resources/Corazon3.png'
DESIRED_FPS = 60
BULLET_IMAGE = 'resources/bullet.png'
BULLET_MOVE_X = 3
BULLET_SPAWN_TIME = 25
BULLETS_AMOUNT = 3 #Bullets que dispara el titan
BULLET_COLLISION_OFFSET = 64
BULLET_POOL_SIZE = 3
ENEMY_1_IMAGE = 'resources/soupdungeon_2x/titan_2x.png'